export const PRODUCTS_NAME = [
  {
    gameId: 1,
    gameName: "Sports Lord",
    gameRoute: "/sports-lord/dashboard",
    gameIcon: "fas fa-money-bill",
    gameDescription: "*713*22#",
    gameShortcode: "*713*22#",
    gameRouteJoined: "sports-lord",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.png",
  },
  {
    gameId: 2,
    gameName: "Love Relationships",
    gameRoute: "/love-relationships-lord/dashboard",
    gameIcon: "fas fa-heart",
    gameDescription: "*713*22#",
    gameShortcode: "*713*22#",
    gameRouteJoined: "love-relationships-lord",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.png",  
  },
  {
    gameId: 3,
    gameName: "Jobs Alerts",
    gameRoute: "/jobs-lord/dashboard",
    gameIcon: "fas fa-briefcase",
    gameDescription: "*713*22#",
    gameShortcode: "*713*22#",
    gameRouteJoined: "jobs-lord",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.png",
  },
  {
    gameId: 4,
    gameName: "Finance",
    gameRoute: "/finance-lord/dashboard",
    gameIcon: "fas fa-money-bill",
    gameDescription: "*713*22#",
    gameShortcode: "*713*22#",
    gameRouteJoined: "finance-lord",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.png",
  },
  {
    gameId: 5,
    gameName: "Motivation",
    gameRoute: "/motivation-lord/dashboard",
    gameIcon: "fas fa-lightbulb",
    gameDescription: "*713*22#",
    gameShortcode: "*713*22#",
    gameRouteJoined: "motivation-lord",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.png",
  }
];
