export const PRODUCTS_NAME = [
  {
    gameId: 1,
    gameName: "Sports Lord",
    gameRoute: "/sports-lord/dashboard",
    gameIcon: "fas fa-money-bill",
    gameDescription: "*713*22#",
    gameShortcode: "*713*22#",
    gameRouteJoined: "sports-lord",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.png",
  },
  {
    gameId: 2,
    gameName: "Bet Lord",
    gameRoute: "/sports-lord/dashboard",
    gameIcon: "fas fa-money-bill",
    gameDescription: "*",
    gameShortcode: "*713*22#",
    gameRouteJoined: "sports-lord",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.png",
  },
  {
    gameId: 3,
    gameName: "Big Money",
    gameRoute: "/sports-lord/dashboard",
    gameIcon: "fas fa-money-bill",
    gameDescription: "*",
    gameShortcode: "*713*22#",
    gameRouteJoined: "sports-lord",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.png",
  }
];
